frase = 'O tiago é legal'
frase = frase.replace('tiago','livia')
dividido = frase.split()
print(dividido[2],[1])
print(frase)
print(len(frase.strip()))
print(frase[1:16:2])
print(frase)
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(len(frase))
print(frase.count('o'))
print(frase.replace('tiago','livia'))
print(frase.find('tiago'))
print('tiago' in frase)
print(frase.lstrip())

print(frase.split())
